[package]
name = "openh264"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openh264-sys2 = { path = "../openh264-sys2" }

[dev-dependencies]
image = "0.23"