
name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: LFS Checkout
      run: git lfs checkout
    - name: Version
      run: rustc -Vv
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: cargo test --verbose -- --test-threads=1 --nocapture
